### ISSUE TITLE
Everoute 1.0.2 agent container crash on kubernetes 1.21.9

### ISSUE THREAD

**Issue by zwtop** [everoute/everoute#367]
```
root@skydive:~# kubectl logs -n kube-system   everoute-agent-wcwkq everoute-agent -f
time="2022-02-09T09:58:41Z" level=info msg="/var/run/openvswitch/cnibr0.mgmt is disconnected, connecting..."
time="2022-02-09T09:58:41Z" level=info msg="/var/run/openvswitch/cnibr0-policy.mgmt is disconnected, connecting..."
time="2022-02-09T09:58:41Z" level=info msg="Connecting to socket file /var/run/openvswitch/cnibr0.mgmt"
time="2022-02-09T09:58:41Z" level=info msg="/var/run/openvswitch/cnibr0-uplink.mgmt is disconnected, connecting..."
time="2022-02-09T09:58:41Z" level=info msg="Connecting to socket file /var/run/openvswitch/cnibr0-uplink.mgmt"
time="2022-02-09T09:58:41Z" level=info msg="/var/run/openvswitch/cnibr0-cls.mgmt is disconnected, connecting..."
time="2022-02-09T09:58:41Z" level=info msg="Connecting to socket file /var/run/openvswitch/cnibr0-cls.mgmt"
time="2022-02-09T09:58:41Z" level=info msg="New connection.."
time="2022-02-09T09:58:41Z" level=info msg="Connecting to socket file /var/run/openvswitch/cnibr0-policy.mgmt"
time="2022-02-09T09:58:41Z" level=info msg="New connection.."
time="2022-02-09T09:58:41Z" level=info msg="Received Openflow 1.3 Hello message"
time="2022-02-09T09:58:41Z" level=info msg="Received Openflow 1.3 Hello message"
time="2022-02-09T09:58:41Z" level=info msg="New connection.."
time="2022-02-09T09:58:41Z" level=info msg="Received Openflow 1.3 Hello message"
time="2022-02-09T09:58:41Z" level=info msg="Received ofp1.3 Switch feature response: {Header:{Version:4 Type:6 Length:32 Xid:7} DPID:00:00:e6:c4:03:43:30:46 Buffers:0 NumTables:254 AuxilaryId:0 pad:[0 0] Capabilities:79 Actions:0 Ports:[]}"
time="2022-02-09T09:58:41Z" level=info msg="Openflow Connection for new switch: 00:00:e6:c4:03:43:30:46"
time="2022-02-09T09:58:41Z" level=info msg="Switch cnibr0-policy connected"
time="2022-02-09T09:58:41Z" level=info msg="Received ofp1.3 Switch feature response: {Header:{Version:4 Type:6 Length:32 Xid:4} DPID:00:00:42:c8:d1:e0:7b:44 Buffers:0 NumTables:254 AuxilaryId:0 pad:[0 0] Capabilities:79 Actions:0 Ports:[]}"
time="2022-02-09T09:58:41Z" level=info msg="Received ofp1.3 Switch feature response: {Header:{Version:4 Type:6 Length:32 Xid:5} DPID:00:00:72:be:df:c1:64:4a Buffers:0 NumTables:254 AuxilaryId:0 pad:[0 0] Capabilities:79 Actions:0 Ports:[]}"
time="2022-02-09T09:58:41Z" level=info msg="Openflow Connection for new switch: 00:00:72:be:df:c1:64:4a"
time="2022-02-09T09:58:41Z" level=info msg="Switch cnibr0-cls connected"
time="2022-02-09T09:58:41Z" level=info msg="Openflow Connection for new switch: 00:00:42:c8:d1:e0:7b:44"
time="2022-02-09T09:58:41Z" level=info msg="Switch cnibr0-uplink connected"
time="2022-02-09T09:58:41Z" level=info msg="New connection.."
time="2022-02-09T09:58:41Z" level=info msg="Received Openflow 1.3 Hello message"
time="2022-02-09T09:58:41Z" level=info msg="Received ofp1.3 Switch feature response: {Header:{Version:4 Type:6 Length:32 Xid:21} DPID:00:00:4e:f1:42:61:f3:4f Buffers:0 NumTables:254 AuxilaryId:0 pad:[0 0] Capabilities:79 Actions:0 Ports:[]}"
time="2022-02-09T09:58:41Z" level=info msg="Openflow Connection for new switch: 00:00:4e:f1:42:61:f3:4f"
time="2022-02-09T09:58:41Z" level=info msg="Switch cnibr0 connected"
time="2022-02-09T09:58:42Z" level=info msg="Bridge's external-ids are empty"
time="2022-02-09T09:58:42Z" level=info msg="Add file watcher for file: /var/run/openvswitch/db.sock"
panic: runtime error: index out of range [0] with length 0

goroutine 1 [running]:
main.setAgentConf(0xc0000fa090, 0x7f20208b93c0, 0xc000357a10)
        /go/src/everoute/cmd/everoute-agent/config.go:128 +0x911
main.main()
        /go/src/everoute/cmd/everoute-agent/main.go:81 +0x7f5
```

```
root@skydive:~# kubectl get po -A
NAMESPACE     NAME                                   READY   STATUS              RESTARTS   AGE
kube-system   coredns-558bd4d5db-j877w               0/1     ContainerCreating   0          16m
kube-system   coredns-558bd4d5db-xhqjr               0/1     ContainerCreating   0          16m
kube-system   etcd-skydive                           1/1     Running             0          17m
kube-system   everoute-agent-wcwkq                   1/2     CrashLoopBackOff    1          27s
kube-system   everoute-controller-867879c886-r7d9f   1/1     Running             0          68s
kube-system   kube-apiserver-skydive                 1/1     Running             0          16m
kube-system   kube-controller-manager-skydive        1/1     Running             0          16m
kube-system   kube-proxy-gzvsx                       1/1     Running             0          16m
kube-system   kube-scheduler-skydive                 1/1     Running             0          16m
```

**Comment by zwtop** [comment]
This is caused by missing PodCIDR when setup kubernetes cluster, we need more logs here to locate the issue.

**Comment by zwtop** [comment]
Documents: https://github.com/everoute/everoute/blob/main/docs/cni/README.md#kubernetes-cluster
