### ISSUE TITLE
Agent panic on OVS restart

### ISSUE THREAD

**Issue by zwtop** [everoute/everoute#452]
```
=== RUN   TestDpManager/restart_ovs-vswitchd
time="2022-05-23T09:40:23Z" level=warning msg="InboundError EOF" 
time="2022-05-23T09:40:23Z" level=info msg="Closing OpenFlow message stream." 
time="2022-05-23T09:40:23Z" level=warning msg="InboundError EOF" 
time="2022-05-23T09:40:23Z" level=info msg="Closing OpenFlow message stream." 
time="2022-05-23T09:40:23Z" level=warning msg="InboundError EOF" 
time="2022-05-23T09:40:23Z" level=info msg="Closing OpenFlow message stream." 
time="2022-05-23T09:40:23Z" level=warning msg="InboundError EOF" 
time="2022-05-23T09:40:23Z" level=info msg="Closing OpenFlow message stream." 
time="2022-05-23T09:40:23Z" level=warning msg="Received ERROR message from switch 00:00:62:99:4f:05:7b:4e. Err: EOF" 
time="2022-05-23T09:40:23Z" level=info msg="Switch ovsbr0 disconnected" 
time="2022-05-23T09:40:23Z" level=info msg="/var/run/openvswitch/ovsbr0.mgmt is disconnected, connecting..." 
time="2022-05-23T09:40:23Z" level=info msg="Connecting to socket file /var/run/openvswitch/ovsbr0.mgmt" 
time="2022-05-23T09:40:23Z" level=info msg="New connection.." 
time="2022-05-23T09:40:23Z" level=warning msg="Received ERROR message from switch 00:00:46:e4:87:96:1d:48. Err: EOF" 
time="2022-05-23T09:40:23Z" level=info msg="Switch ovsbr0-cls disconnected" 
time="2022-05-23T09:40:23Z" level=info msg="/var/run/openvswitch/ovsbr0-cls.mgmt is disconnected, connecting..." 
time="2022-05-23T09:40:23Z" level=warning msg="Received ERROR message from switch 00:00:ba:43:0a:ea:1b:49. Err: EOF" 
time="2022-05-23T09:40:23Z" level=info msg="Switch ovsbr0-uplink disconnected" 
time="2022-05-23T09:40:23Z" level=info msg="/var/run/openvswitch/ovsbr0-uplink.mgmt is disconnected, connecting..." 
time="2022-05-23T09:40:23Z" level=warning msg="Received ERROR message from switch 00:00:0e:f4:b2:c0:f5:45. Err: EOF" 
time="2022-05-23T09:40:23Z" level=info msg="Switch ovsbr0-policy disconnected" 
time="2022-05-23T09:40:23Z" level=info msg="/var/run/openvswitch/ovsbr0-policy.mgmt is disconnected, connecting..." 
time="2022-05-23T09:40:23Z" level=warning msg="OutboundError: write unix @->/var/run/openvswitch/ovsbr0.mgmt: write: broken pipe" 
time="2022-05-23T09:40:23Z" level=info msg="Closing OpenFlow message stream." 
time="2022-05-23T09:40:23Z" level=info msg="message stream error write unix @->/var/run/openvswitch/ovsbr0.mgmt: write: broken pipe" 
time="2022-05-23T09:40:23Z" level=info msg="Received vds ovsbr0 bridge local reconnect event" 
=== RUN   TestDpManager/validate_default_Flow_replay
time="2022-05-23T09:40:25Z" level=info msg="Connecting to socket file /var/run/openvswitch/ovsbr0-uplink.mgmt" 
time="2022-05-23T09:40:25Z" level=info msg="New connection.." 
time="2022-05-23T09:40:25Z" level=info msg="Received Openflow 1.3 Hello message" 
time="2022-05-23T09:40:25Z" level=info msg="Connecting to socket file /var/run/openvswitch/ovsbr0-cls.mgmt" 
time="2022-05-23T09:40:25Z" level=info msg="New connection.." 
time="2022-05-23T09:40:25Z" level=info msg="Connecting to socket file /var/run/openvswitch/ovsbr0-policy.mgmt" 
time="2022-05-23T09:40:25Z" level=info msg="New connection.." 
time="2022-05-23T09:40:25Z" level=info msg="Received Openflow 1.3 Hello message" 
time="2022-05-23T09:40:25Z" level=info msg="Received Openflow 1.3 Hello message" 
time="2022-05-23T09:40:25Z" level=info msg="Received ofp1.3 Switch feature response: {Header:{Version:4 Type:6 Length:32 Xid:100} DPID:00:00:ba:43:0a:ea:1b:49 Buffers:0 NumTables:254 AuxilaryId:0 pad:[0 0] Capabilities:79 Actions:0 Ports:[]}" 
time="2022-05-23T09:40:25Z" level=info msg="Openflow Connection for new switch: 00:00:ba:43:0a:ea:1b:49" 
time="2022-05-23T09:40:25Z" level=info msg="Switch ovsbr0-uplink connected" 
time="2022-05-23T09:40:25Z" level=info msg="Received ofp1.3 Switch feature response: {Header:{Version:4 Type:6 Length:32 Xid:103} DPID:00:00:46:e4:87:96:1d:48 Buffers:0 NumTables:254 AuxilaryId:0 pad:[0 0] Capabilities:79 Actions:0 Ports:[]}" 
time="2022-05-23T09:40:25Z" level=info msg="Openflow Connection for new switch: 00:00:46:e4:87:96:1d:48" 
time="2022-05-23T09:40:25Z" level=info msg="Switch ovsbr0-cls connected" 
time="2022-05-23T09:40:25Z" level=info msg="Received vds ovsbr0 bridge cls reconnect event" 
time="2022-05-23T09:40:25Z" level=info msg="Received ofp1.3 Switch feature response: {Header:{Version:4 Type:6 Length:32 Xid:104} DPID:00:00:0e:f4:b2:c0:f5:45 Buffers:0 NumTables:254 AuxilaryId:0 pad:[0 0] Capabilities:79 Actions:0 Ports:[]}" 
time="2022-05-23T09:40:25Z" level=info msg="Openflow Connection for new switch: 00:00:0e:f4:b2:c0:f5:45" 
time="2022-05-23T09:40:25Z" level=info msg="Switch ovsbr0-policy connected" 
time="2022-05-23T09:40:25Z" level=info msg="Received vds ovsbr0 bridge policy reconnect event" 
time="2022-05-23T09:40:25Z" level=info msg="Received vds ovsbr0 bridge uplink reconnect event" 
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x5873a1]

goroutine 170 [running]:
github.com/contiv/ofnet/ofctrl.(*OFSwitch).Send(...)
	/root/go/pkg/mod/github.com/everoute/ofnet@v0.0.0-20211[2290](https://github.com/everoute/everoute/runs/6552684436?check_suite_focus=true#step:3:2291)83707-5cb1e875a38b/ofctrl/ofSwitch.go:111
github.com/contiv/ofnet/ofctrl.(*OFSwitch).DeleteFlowByCookie(0x0, 0x0, 0xffff000000000000)
	/root/go/pkg/mod/github.com/everoute/ofnet@v0.0.0-20211229083707-5cb1e875a38b/ofctrl/fgraphSwitch.go:172 +0x61
github.com/contiv/ofnet/ofctrl.(*OFSwitch).DeleteFlowByRoundInfo(...)
	/root/go/pkg/mod/github.com/everoute/ofnet@v0.0.0-20211229083707-5cb1e875a38b/ofctrl/fgraphSwitch.go:160
github.com/everoute/everoute/pkg/agent/datapath.InitializeVDS.func1({0x68f3cf, 0x6})
	/go/src/github.com/everoute/everoute/pkg/agent/datapath/multiBridgeDatapath.go:509 +0xbc
created by github.com/everoute/everoute/pkg/agent/datapath.InitializeVDS
	/go/src/github.com/everoute/everoute/pkg/agent/datapath/multiBridgeDatapath.go:506 +0xa05
FAIL	github.com/everoute/everoute/pkg/agent/datapath	20.142s
```

**Comment by KeyongSun** [comment]
we hit this kind of issue before, but didn't reproduce, right? cc @echkenluo

**Comment by wu-cl** [comment]
https://github.com/everoute/everoute/runs/7942379663?check_suite_focus=true
